// Mocks generated by Mockito 5.4.6 from annotations
// in heads_up_game/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i13;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:firebase_analytics/firebase_analytics.dart' as _i4;
import 'package:firebase_auth/firebase_auth.dart' as _i3;
import 'package:firebase_crashlytics/firebase_crashlytics.dart' as _i5;
import 'package:firebase_remote_config/firebase_remote_config.dart' as _i6;
import 'package:flutter/material.dart' as _i12;
import 'package:heads_up_game/models/deck.dart' as _i10;
import 'package:heads_up_game/models/game_session.dart' as _i15;
import 'package:heads_up_game/models/video_recording_result.dart' as _i16;
import 'package:heads_up_game/providers/deck_provider.dart' as _i9;
import 'package:heads_up_game/providers/game_provider.dart' as _i14;
import 'package:heads_up_game/services/firebase_service.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseFirestore_0 extends _i1.SmartFake
    implements _i2.FirebaseFirestore {
  _FakeFirebaseFirestore_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseAuth_1 extends _i1.SmartFake implements _i3.FirebaseAuth {
  _FakeFirebaseAuth_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseAnalytics_2 extends _i1.SmartFake
    implements _i4.FirebaseAnalytics {
  _FakeFirebaseAnalytics_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseCrashlytics_3 extends _i1.SmartFake
    implements _i5.FirebaseCrashlytics {
  _FakeFirebaseCrashlytics_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseRemoteConfig_4 extends _i1.SmartFake
    implements _i6.FirebaseRemoteConfig {
  _FakeFirebaseRemoteConfig_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_5 extends _i1.SmartFake implements Duration {
  _FakeDuration_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FirebaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseService extends _i1.Mock implements _i7.FirebaseService {
  MockFirebaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FirebaseFirestore get firestore =>
      (super.noSuchMethod(
            Invocation.getter(#firestore),
            returnValue: _FakeFirebaseFirestore_0(
              this,
              Invocation.getter(#firestore),
            ),
          )
          as _i2.FirebaseFirestore);

  @override
  _i3.FirebaseAuth get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeFirebaseAuth_1(this, Invocation.getter(#auth)),
          )
          as _i3.FirebaseAuth);

  @override
  _i4.FirebaseAnalytics get analytics =>
      (super.noSuchMethod(
            Invocation.getter(#analytics),
            returnValue: _FakeFirebaseAnalytics_2(
              this,
              Invocation.getter(#analytics),
            ),
          )
          as _i4.FirebaseAnalytics);

  @override
  _i5.FirebaseCrashlytics get crashlytics =>
      (super.noSuchMethod(
            Invocation.getter(#crashlytics),
            returnValue: _FakeFirebaseCrashlytics_3(
              this,
              Invocation.getter(#crashlytics),
            ),
          )
          as _i5.FirebaseCrashlytics);

  @override
  _i6.FirebaseRemoteConfig get remoteConfig =>
      (super.noSuchMethod(
            Invocation.getter(#remoteConfig),
            returnValue: _FakeFirebaseRemoteConfig_4(
              this,
              Invocation.getter(#remoteConfig),
            ),
          )
          as _i6.FirebaseRemoteConfig);

  @override
  _i8.Stream<_i3.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i8.Stream<_i3.User?>.empty(),
          )
          as _i8.Stream<_i3.User?>);

  @override
  _i8.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i3.User?> signInAnonymously() =>
      (super.noSuchMethod(
            Invocation.method(#signInAnonymously, []),
            returnValue: _i8.Future<_i3.User?>.value(),
          )
          as _i8.Future<_i3.User?>);

  @override
  _i8.Future<_i3.User?> signInWithEmailPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailPassword, [email, password]),
            returnValue: _i8.Future<_i3.User?>.value(),
          )
          as _i8.Future<_i3.User?>);

  @override
  _i8.Future<_i3.User?> signUpWithEmailPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithEmailPassword, [email, password]),
            returnValue: _i8.Future<_i3.User?>.value(),
          )
          as _i8.Future<_i3.User?>);

  @override
  _i8.Future<void> createUserProfile(_i3.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#createUserProfile, [user]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateUserLastSeen() =>
      (super.noSuchMethod(
            Invocation.method(#updateUserLastSeen, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> logEvent(String? name, {Map<String, dynamic>? parameters}) =>
      (super.noSuchMethod(
            Invocation.method(#logEvent, [name], {#parameters: parameters}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> logScreenView(String? screenName) =>
      (super.noSuchMethod(
            Invocation.method(#logScreenView, [screenName]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [DeckProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeckProvider extends _i1.Mock implements _i9.DeckProvider {
  MockDeckProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i10.Deck> get allDecks =>
      (super.noSuchMethod(
            Invocation.getter(#allDecks),
            returnValue: <_i10.Deck>[],
          )
          as List<_i10.Deck>);

  @override
  List<_i10.Deck> get defaultDecks =>
      (super.noSuchMethod(
            Invocation.getter(#defaultDecks),
            returnValue: <_i10.Deck>[],
          )
          as List<_i10.Deck>);

  @override
  List<_i10.Deck> get customDecks =>
      (super.noSuchMethod(
            Invocation.getter(#customDecks),
            returnValue: <_i10.Deck>[],
          )
          as List<_i10.Deck>);

  @override
  List<_i10.Deck> get freeDecks =>
      (super.noSuchMethod(
            Invocation.getter(#freeDecks),
            returnValue: <_i10.Deck>[],
          )
          as List<_i10.Deck>);

  @override
  List<_i10.Deck> get premiumDecks =>
      (super.noSuchMethod(
            Invocation.getter(#premiumDecks),
            returnValue: <_i10.Deck>[],
          )
          as List<_i10.Deck>);

  @override
  List<_i10.Deck> get unlockedDecks =>
      (super.noSuchMethod(
            Invocation.getter(#unlockedDecks),
            returnValue: <_i10.Deck>[],
          )
          as List<_i10.Deck>);

  @override
  Set<String> get favoriteDecks =>
      (super.noSuchMethod(
            Invocation.getter(#favoriteDecks),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  List<_i10.Deck> get favoriteDecksAsList =>
      (super.noSuchMethod(
            Invocation.getter(#favoriteDecksAsList),
            returnValue: <_i10.Deck>[],
          )
          as List<_i10.Deck>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  String get userCountryCode =>
      (super.noSuchMethod(
            Invocation.getter(#userCountryCode),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#userCountryCode),
            ),
          )
          as String);

  @override
  String get errorMessage =>
      (super.noSuchMethod(
            Invocation.getter(#errorMessage),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#errorMessage),
            ),
          )
          as String);

  @override
  bool get hasError =>
      (super.noSuchMethod(Invocation.getter(#hasError), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i8.Future<void> retryLoading() =>
      (super.noSuchMethod(
            Invocation.method(#retryLoading, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> forceRefresh() =>
      (super.noSuchMethod(
            Invocation.method(#forceRefresh, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i10.Deck>> searchDecksGlobally(String? searchTerm) =>
      (super.noSuchMethod(
            Invocation.method(#searchDecksGlobally, [searchTerm]),
            returnValue: _i8.Future<List<_i10.Deck>>.value(<_i10.Deck>[]),
          )
          as _i8.Future<List<_i10.Deck>>);

  @override
  _i8.Future<bool> createCustomDeck({
    required String? name,
    required String? description,
    required List<String>? cards,
    _i12.IconData? icon,
    _i13.Color? color,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createCustomDeck, [], {
              #name: name,
              #description: description,
              #cards: cards,
              #icon: icon,
              #color: color,
            }),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> updateCustomDeck({
    required String? deckId,
    String? name,
    String? description,
    List<String>? cards,
    _i12.IconData? icon,
    _i13.Color? color,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateCustomDeck, [], {
              #deckId: deckId,
              #name: name,
              #description: description,
              #cards: cards,
              #icon: icon,
              #color: color,
            }),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> deleteCustomDeck(String? deckId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCustomDeck, [deckId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> unlockPremiumDeck(String? deckId) =>
      (super.noSuchMethod(
            Invocation.method(#unlockPremiumDeck, [deckId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  bool isDeckUnlocked(String? deckId) =>
      (super.noSuchMethod(
            Invocation.method(#isDeckUnlocked, [deckId]),
            returnValue: false,
          )
          as bool);

  @override
  _i10.Deck? getDeckById(String? id) =>
      (super.noSuchMethod(Invocation.method(#getDeckById, [id])) as _i10.Deck?);

  @override
  List<_i10.Deck> searchDecks(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchDecks, [query]),
            returnValue: <_i10.Deck>[],
          )
          as List<_i10.Deck>);

  @override
  _i8.Future<List<String>> getRecentDeckIds() =>
      (super.noSuchMethod(
            Invocation.method(#getRecentDeckIds, []),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<void> addToRecentDecks(String? deckId) =>
      (super.noSuchMethod(
            Invocation.method(#addToRecentDecks, [deckId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> addToFavorites(String? deckId) =>
      (super.noSuchMethod(
            Invocation.method(#addToFavorites, [deckId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> removeFromFavorites(String? deckId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromFavorites, [deckId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  bool isFavorite(String? deckId) =>
      (super.noSuchMethod(
            Invocation.method(#isFavorite, [deckId]),
            returnValue: false,
          )
          as bool);

  @override
  _i8.Future<List<_i10.Deck>> getRecentDecks() =>
      (super.noSuchMethod(
            Invocation.method(#getRecentDecks, []),
            returnValue: _i8.Future<List<_i10.Deck>>.value(<_i10.Deck>[]),
          )
          as _i8.Future<List<_i10.Deck>>);

  @override
  _i8.Future<void> refreshData() =>
      (super.noSuchMethod(
            Invocation.method(#refreshData, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [GameProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameProvider extends _i1.Mock implements _i14.GameProvider {
  MockGameProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Duration get remainingTime =>
      (super.noSuchMethod(
            Invocation.getter(#remainingTime),
            returnValue: _FakeDuration_5(
              this,
              Invocation.getter(#remainingTime),
            ),
          )
          as Duration);

  @override
  bool get isGameActive =>
      (super.noSuchMethod(Invocation.getter(#isGameActive), returnValue: false)
          as bool);

  @override
  List<_i15.GameSession> get gameHistory =>
      (super.noSuchMethod(
            Invocation.getter(#gameHistory),
            returnValue: <_i15.GameSession>[],
          )
          as List<_i15.GameSession>);

  @override
  Map<String, dynamic> get statistics =>
      (super.noSuchMethod(
            Invocation.getter(#statistics),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  int get roundDuration =>
      (super.noSuchMethod(Invocation.getter(#roundDuration), returnValue: 0)
          as int);

  @override
  bool get soundEnabled =>
      (super.noSuchMethod(Invocation.getter(#soundEnabled), returnValue: false)
          as bool);

  @override
  bool get vibrationEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#vibrationEnabled),
            returnValue: false,
          )
          as bool);

  @override
  bool get kidFriendlyMode =>
      (super.noSuchMethod(
            Invocation.getter(#kidFriendlyMode),
            returnValue: false,
          )
          as bool);

  @override
  bool get showWordsAfterPass =>
      (super.noSuchMethod(
            Invocation.getter(#showWordsAfterPass),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void startGame({
    required _i10.Deck? deck,
    bool? isTeamMode = false,
    List<String>? teamNames,
    int? totalRounds = 1,
  }) => super.noSuchMethod(
    Invocation.method(#startGame, [], {
      #deck: deck,
      #isTeamMode: isTeamMode,
      #teamNames: teamNames,
      #totalRounds: totalRounds,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void markCorrect() => super.noSuchMethod(
    Invocation.method(#markCorrect, []),
    returnValueForMissingStub: null,
  );

  @override
  void markPass() => super.noSuchMethod(
    Invocation.method(#markPass, []),
    returnValueForMissingStub: null,
  );

  @override
  void togglePause() => super.noSuchMethod(
    Invocation.method(#togglePause, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> endGame() =>
      (super.noSuchMethod(
            Invocation.method(#endGame, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void nextTeam() => super.noSuchMethod(
    Invocation.method(#nextTeam, []),
    returnValueForMissingStub: null,
  );

  @override
  void playAgain() => super.noSuchMethod(
    Invocation.method(#playAgain, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> updateRoundDuration(int? seconds) =>
      (super.noSuchMethod(
            Invocation.method(#updateRoundDuration, [seconds]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> toggleSound() =>
      (super.noSuchMethod(
            Invocation.method(#toggleSound, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> toggleVibration() =>
      (super.noSuchMethod(
            Invocation.method(#toggleVibration, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> toggleKidFriendlyMode() =>
      (super.noSuchMethod(
            Invocation.method(#toggleKidFriendlyMode, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> toggleShowWordsAfterPass() =>
      (super.noSuchMethod(
            Invocation.method(#toggleShowWordsAfterPass, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getGlobalLeaderboard({
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getGlobalLeaderboard, [], {#limit: limit}),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getDeckLeaderboard(
    String? deckId, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDeckLeaderboard, [deckId], {#limit: limit}),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<void> refreshData() =>
      (super.noSuchMethod(
            Invocation.method(#refreshData, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  Map<String, dynamic> getStatistics() =>
      (super.noSuchMethod(
            Invocation.method(#getStatistics, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  void doubleLastGameScore() => super.noSuchMethod(
    Invocation.method(#doubleLastGameScore, []),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, double> getAchievementProgress() =>
      (super.noSuchMethod(
            Invocation.method(#getAchievementProgress, []),
            returnValue: <String, double>{},
          )
          as Map<String, double>);

  @override
  _i8.Future<void> clearAllData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllData, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void setVideoRecording(_i16.VideoRecordingResult? recording) =>
      super.noSuchMethod(
        Invocation.method(#setVideoRecording, [recording]),
        returnValueForMissingStub: null,
      );

  @override
  void clearVideoRecording() => super.noSuchMethod(
    Invocation.method(#clearVideoRecording, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
