import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

class DefaultDecks {
  static final List<Map<String, dynamic>> decks = [
    {
      'id': '10000000-0000-4000-a000-000000000001',
      'name': 'Emotions & Feelings',
      'description': 'Express and guess different emotions and feelings!',
      'icon': FontAwesomeIcons.faceSmile,
      'color': const Color(0xFFE91E63),
      'isPremium': false,
      'cards': [
        'Happy', 'Sad', 'Angry', 'Excited', 'Nervous', 'Jealous', 'Confused',
        'Proud', 'Embarrassed', 'Grateful', 'Surprised', 'Disgusted', 'Anxious',
        'Bored', 'Hopeful', 'Lonely', 'Shy', 'Frustrated', 'Content', 'Fearful',
        'Overwhelmed', 'Relieved', 'Curious', 'Nostalgic', 'Guilty', 'Amused',
        'Determined', 'Peaceful', 'Grumpy', 'Cheerful', 'Terrified', 'Gloomy',
        'Ecstatic', 'Furious', 'Heartbroken', 'Amazed', 'Worried', 'Stubborn',
        'Thoughtful', 'Impatient', 'Moody', 'Playful', 'Sarcastic', 'Dramatic',
        'Courageous',
      ],
    },
    {
      'id': '10000000-0000-4000-a000-000000000002',
      'name': 'Celebrities',
      'description': 'Famous people from movies, music, sports and more!',
      'icon': FontAwesomeIcons.star,
      'color': const Color(0xFFFFD93D),
      'isPremium': false,
      'cards': [
        'Taylor Swift', 'Cristiano Ronaldo', 'Beyonce', 'Tom Hanks', 'Elon Musk',
        'Rihanna', 'Lionel Messi', 'Oprah Winfrey', 'Dwayne Johnson', 'Adele',
        'Leonardo DiCaprio', 'Kim Kardashian', 'Drake', 'Selena Gomez',
        'Ariana Grande', 'Brad Pitt', 'Lady Gaga', 'Justin Bieber',
        'Scarlett Johansson', 'Will Smith', 'Ed Sheeran', 'Jennifer Lopez',
        'Chris Hemsworth', 'Emma Watson', 'Robert Downey Jr.', 'Billie Eilish',
        'Tom Cruise', 'Shakira', 'LeBron James', 'Katy Perry', 'Bruno Mars',
        'Zendaya', 'Post Malone', 'Margot Robbie', 'Bad Bunny', 'Cardi B',
        'Ryan Reynolds', 'Angelina Jolie', 'Travis Kelce', 'Miley Cyrus',
        'Morgan Freeman', 'Keanu Reeves', 'Gal Gadot', 'Nicki Minaj',
        'The Weeknd',
      ],
    },
    {
      'id': '10000000-0000-4000-a000-000000000003',
      'name': 'Tasty Food',
      'description': 'Delicious foods and dishes from around the world!',
      'icon': FontAwesomeIcons.utensils,
      'color': const Color(0xFFFF9800),
      'isPremium': false,
      'cards': [
        'Pizza', 'Sushi', 'Tacos', 'Pasta', 'Burger', 'Ice Cream', 'Pancakes',
        'Fried Chicken', 'Chocolate Cake', 'French Fries', 'Hot Dog', 'Steak',
        'Dumplings', 'Nachos', 'Waffles', 'Ramen', 'Sandwich', 'Donut',
        'Popcorn', 'Lasagna', 'Cupcake', 'Burrito', 'Cheesecake', 'Fried Rice',
        'Fish and Chips', 'Croissant', 'Milkshake', 'Mac and Cheese',
        'Spring Rolls', 'Brownies', 'Pad Thai', 'Kebab', 'Churros',
        'Chicken Wings', 'Cinnamon Roll', 'Onion Rings', 'Garlic Bread',
        'Mashed Potatoes', 'Corn Dog', 'Banana Split', 'BBQ Ribs',
        'Grilled Cheese', 'Mozzarella Sticks', 'Cotton Candy', 'Apple Pie',
      ],
    },
    {
      'id': '10000000-0000-4000-a000-000000000004',
      'name': 'Animals',
      'description': 'Wild, domestic and exotic animals from everywhere!',
      'icon': FontAwesomeIcons.paw,
      'color': const Color(0xFF4CAF50),
      'isPremium': false,
      'cards': [
        'Lion', 'Elephant', 'Penguin', 'Dolphin', 'Eagle', 'Octopus',
        'Kangaroo', 'Chameleon', 'Giraffe', 'Tiger', 'Monkey', 'Shark',
        'Butterfly', 'Panda', 'Parrot', 'Koala', 'Crocodile', 'Flamingo',
        'Wolf', 'Hippopotamus', 'Cheetah', 'Polar Bear', 'Jellyfish',
        'Rhinoceros', 'Hummingbird', 'Gorilla', 'Seahorse', 'Sloth',
        'Peacock', 'Lobster', 'Bat', 'Owl', 'Tortoise', 'Zebra', 'Whale',
        'Fox', 'Hedgehog', 'Rattlesnake', 'Toucan', 'Moose', 'Camel',
        'Squirrel', 'Stingray', 'Pelican', 'Armadillo',
      ],
    },
    {
      'id': '10000000-0000-4000-a000-000000000005',
      'name': 'Mix',
      'description': 'A fun mix of random things, actions and ideas!',
      'icon': FontAwesomeIcons.shuffle,
      'color': const Color(0xFF3F51B5),
      'isPremium': false,
      'cards': [
        'Umbrella', 'Skyscraper', 'Yoga', 'Volcano', 'Astronaut',
        'Roller Coaster', 'Selfie', 'Trampoline', 'Telescope', 'Pirate',
        'Snowboarding', 'Magician', 'Skateboard', 'Lighthouse', 'Karate',
        'Robot', 'Bungee Jumping', 'Campfire', 'Parachute', 'Ninja',
        'Surfing', 'Disco Ball', 'Hot Air Balloon', 'Snowman', 'Juggling',
        'Scuba Diving', 'Treehouse', 'Fireworks', 'Hammock', 'Limousine',
        'Zipline', 'Sombrero', 'Viking', 'Waterfall', 'Bowling',
        'Carnival', 'Submarine', 'Windmill', 'Catapult',
        'Mariachi', 'Gondola', 'Safari', 'Gymnastics', 'Boomerang',
      ],
    },
    {
      'id': '10000000-0000-4000-a000-000000000006',
      'name': 'Just For Kids',
      'description': 'Simple and fun words perfect for young players!',
      'icon': FontAwesomeIcons.child,
      'color': const Color(0xFF8BC34A),
      'isPremium': false,
      'cards': [
        'Balloon', 'Rainbow', 'Dinosaur', 'Ice Cream', 'Puppy', 'Butterfly',
        'Robot', 'Princess', 'Dragon', 'Pirate', 'Unicorn', 'Superman',
        'Mermaid', 'Rocket', 'Teddy Bear', 'Clown', 'Fairy', 'Monster',
        'Cowboy', 'Snowman', 'Monkey', 'Castle', 'Train', 'Spider',
        'Astronaut', 'Wizard', 'Pumpkin', 'Elephant', 'Airplane', 'Lion',
        'Cookie', 'Dolphin', 'Penguin', 'Superhero', 'Ghost', 'Ninja',
        'Kangaroo', 'Banana', 'Fireman', 'Giraffe', 'Cupcake',
        'Chicken', 'Kitten', 'Treasure',
      ],
    },
    {
      'id': '10000000-0000-4000-a000-000000000007',
      'name': 'Countries',
      'description': 'Guess countries from all around the globe!',
      'icon': FontAwesomeIcons.globe,
      'color': const Color(0xFF2196F3),
      'isPremium': false,
      'cards': [
        'United States', 'Japan', 'Brazil', 'Australia', 'Egypt', 'India',
        'France', 'Canada', 'Mexico', 'Italy', 'Germany', 'China',
        'South Korea', 'Spain', 'Russia', 'United Kingdom', 'Argentina',
        'South Africa', 'Thailand', 'Turkey', 'Greece', 'Sweden',
        'Switzerland', 'New Zealand', 'Nigeria', 'Colombia', 'Norway',
        'Ireland', 'Portugal', 'Netherlands', 'Poland', 'Philippines',
        'Indonesia', 'Vietnam', 'Chile', 'Peru', 'Morocco', 'Kenya',
        'Cuba', 'Iceland', 'Jamaica', 'Singapore', 'Malaysia', 'Nepal',
        'Croatia',
      ],
    },
    {
      'id': '10000000-0000-4000-a000-000000000008',
      'name': 'Cars',
      'description': 'Car brands, models and everything automotive!',
      'icon': FontAwesomeIcons.car,
      'color': const Color(0xFF9E9E9E),
      'isPremium': false,
      'cards': [
        'Ferrari', 'Tesla', 'BMW', 'Toyota', 'Mercedes-Benz', 'Lamborghini',
        'Porsche', 'Audi', 'Ford', 'Chevrolet', 'Honda', 'Rolls-Royce',
        'Bugatti', 'Jeep', 'Volkswagen', 'Nissan', 'Range Rover', 'Maserati',
        'Bentley', 'Jaguar', 'Mini Cooper', 'Dodge', 'Subaru', 'Mazda',
        'Cadillac', 'Hyundai', 'Kia', 'Aston Martin', 'McLaren',
        'Alfa Romeo', 'Lexus', 'Volvo', 'Mustang', 'Corvette', 'Camaro',
        'Land Cruiser', 'Hummer', 'Fiat', 'Suzuki', 'Pagani',
        'Pickup Truck', 'Convertible', 'Monster Truck', 'Go-Kart',
        'Formula 1 Car',
      ],
    },
    {
      'id': '10000000-0000-4000-a000-000000000009',
      'name': 'Music Instruments',
      'description': 'Musical instruments from classical to modern!',
      'icon': FontAwesomeIcons.music,
      'color': const Color(0xFFFF5722),
      'isPremium': false,
      'cards': [
        'Guitar', 'Piano', 'Drums', 'Violin', 'Trumpet', 'Flute',
        'Saxophone', 'Harmonica', 'Cello', 'Harp', 'Ukulele', 'Banjo',
        'Accordion', 'Tambourine', 'Xylophone', 'Clarinet', 'Trombone',
        'Bagpipes', 'Bongos', 'Maracas', 'Mandolin', 'Organ', 'Oboe',
        'Bass Guitar', 'Triangle', 'Sitar', 'Didgeridoo', 'Tuba',
        'French Horn', 'Castanets', 'Recorder', 'Keyboard', 'Djembe',
        'Electric Guitar', 'Cymbals', 'Cowbell', 'Piccolo', 'Steel Drum',
        'Synthesizer', 'Kalimba', 'Pan Flute', 'Lyre', 'Conga',
        'Timpani', 'Glockenspiel',
      ],
    },
    {
      'id': '10000000-0000-4000-a000-000000000010',
      'name': 'Historical Figures',
      'description': 'Famous people who shaped our world history!',
      'icon': FontAwesomeIcons.landmark,
      'color': const Color(0xFF795548),
      'isPremium': false,
      'cards': [
        'Albert Einstein', 'Cleopatra', 'Napoleon', 'Leonardo da Vinci',
        'Mahatma Gandhi', 'Martin Luther King Jr.', 'Abraham Lincoln',
        'Queen Elizabeth II', 'Winston Churchill', 'Nelson Mandela',
        'Alexander the Great', 'Julius Caesar', 'William Shakespeare',
        'Mozart', 'Beethoven', 'Marie Curie', 'Nikola Tesla',
        'Christopher Columbus', 'George Washington', 'Thomas Edison',
        'Genghis Khan', 'Frida Kahlo', 'Charles Darwin', 'Galileo Galilei',
        'Joan of Arc', 'Marco Polo', 'Aristotle', 'Confucius',
        'Queen Victoria', 'Amelia Earhart', 'Rosa Parks', 'Tutankhamun',
        'Michelangelo', 'Isaac Newton', 'Benjamin Franklin',
        'Pablo Picasso', 'Florence Nightingale', 'Neil Armstrong',
        'Socrates', 'Plato', 'Anne Frank', 'Pocahontas',
        'Harriet Tubman', 'Wright Brothers', 'Mother Teresa',
      ],
    },
  ];

  static Map<String, dynamic> getDeckById(String id) {
    return decks.firstWhere(
      (deck) => deck['id'] == id,
      orElse: () => decks.first,
    );
  }

  static List<Map<String, dynamic>> getFreeDecks() {
    return decks.where((deck) => deck['isPremium'] == false).toList();
  }

  static List<Map<String, dynamic>> getPremiumDecks() {
    return decks.where((deck) => deck['isPremium'] == true).toList();
  }
}
