import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

class DefaultDecks {
  static final List<Map<String, dynamic>> decks = [
    {
      'id': 'animals',
      'name': 'Animals',
      'description': 'Act out your favorite animals!',
      'icon': FontAwesomeIcons.paw,
      'color': const Color(0xFF6BCF7F),
      'isPremium': false,
      'cards': [
        'Lion',
        'Elephant',
        'Giraffe',
        'Monkey',
        'Penguin',
        'Kangaroo',
        'Dolphin',
        'Eagle',
        'Snake',
        'Butterfly',
        'Tiger',
        'Bear',
        'Rabbit',
        'Horse',
        'Dog',
        'Cat',
        'Mouse',
        'Owl',
        'Peacock',
        'Zebra',
      ],
    },
    {
      'id': 'movies',
      'name': 'Movies',
      'description': 'Famous movies and film characters',
      'icon': FontAwesomeIcons.film,
      'color': const Color(0xFFFF6B6B),
      'isPremium': false,
      'cards': [
        'Titanic',
        'Avatar',
        'Star Wars',
        'Harry Potter',
        'The Matrix',
        'Inception',
        'The Lion King',
        'Frozen',
        'Jurassic Park',
        'E.T.',
        'Forrest Gump',
        'The Godfather',
        'Batman',
        'Spider-Man',
        'Iron Man',
      ],
    },
    {
      'id': 'celebrities',
      'name': 'Celebrities',
      'description': 'Famous people from around the world',
      'icon': FontAwesomeIcons.star,
      'color': const Color(0xFFFFD93D),
      'isPremium': false,
      'cards': [
        'Brad Pitt',
        'Angelina Jolie',
        'Tom Cruise',
        'Jennifer Lawrence',
        'Leonardo DiCaprio',
        'Scarlett Johansson',
        'Will Smith',
        'Emma Watson',
        'Robert Downey Jr.',
        'Chris Hemsworth',
        'Taylor Swift',
        'Beyoncé',
        'Drake',
        'Ariana Grande',
        'Ed Sheeran',
      ],
    },
    {
      'id': 'actions',
      'name': 'Act It Out',
      'description': 'Actions and activities to perform',
      'icon': FontAwesomeIcons.personRunning,
      'color': const Color(0xFF4ECDC4),
      'isPremium': false,
      'cards': [
        'Dancing',
        'Singing',
        'Jumping',
        'Running',
        'Swimming',
        'Cooking',
        'Painting',
        'Reading',
        'Writing',
        'Sleeping',
        'Laughing',
        'Crying',
        'Yawning',
        'Sneezing',
        'Eating',
      ],
    },
    {
      'id': 'kids',
      'name': 'For Kids',
      'description': 'Easy words perfect for children',
      'icon': FontAwesomeIcons.child,
      'color': const Color(0xFF6BCF7F),
      'isPremium': false,
      'cards': [
        'Happy',
        'Sad',
        'Big',
        'Small',
        'Hot',
        'Cold',
        'Sun',
        'Moon',
        'Star',
        'Rain',
        'Tree',
        'Flower',
        'House',
        'Car',
        'Ball',
      ],
    },
    {
      'id': 'superheroes',
      'name': 'Superheroes',
      'description': 'Marvel, DC, and more!',
      'icon': FontAwesomeIcons.mask,
      'color': const Color(0xFF6C63FF),
      'isPremium': true,
      'cards': [
        'Superman',
        'Batman',
        'Spider-Man',
        'Iron Man',
        'Captain America',
        'Thor',
        'Hulk',
        'Black Widow',
        'Wonder Woman',
        'Aquaman',
        'The Flash',
        'Green Lantern',
        'Black Panther',
        'Doctor Strange',
        'Ant-Man',
      ],
    },
  ];

  static Map<String, dynamic> getDeckById(String id) {
    return decks.firstWhere(
      (deck) => deck['id'] == id,
      orElse: () => decks.first,
    );
  }

  static List<Map<String, dynamic>> getFreeDecks() {
    return decks.where((deck) => deck['isPremium'] == false).toList();
  }

  static List<Map<String, dynamic>> getPremiumDecks() {
    return decks.where((deck) => deck['isPremium'] == true).toList();
  }
}
