// Mocks generated by Mockito 5.4.6 from annotations
// in heads_up_game/test/screens/home_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i6;

import 'package:flutter/material.dart' as _i5;
import 'package:heads_up_game/models/deck.dart' as _i3;
import 'package:heads_up_game/models/game_session.dart' as _i8;
import 'package:heads_up_game/providers/deck_provider.dart' as _i2;
import 'package:heads_up_game/providers/game_provider.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DeckProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeckProvider extends _i1.Mock implements _i2.DeckProvider {
  MockDeckProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Deck> get allDecks =>
      (super.noSuchMethod(
            Invocation.getter(#allDecks),
            returnValue: <_i3.Deck>[],
          )
          as List<_i3.Deck>);

  @override
  List<_i3.Deck> get defaultDecks =>
      (super.noSuchMethod(
            Invocation.getter(#defaultDecks),
            returnValue: <_i3.Deck>[],
          )
          as List<_i3.Deck>);

  @override
  List<_i3.Deck> get customDecks =>
      (super.noSuchMethod(
            Invocation.getter(#customDecks),
            returnValue: <_i3.Deck>[],
          )
          as List<_i3.Deck>);

  @override
  List<_i3.Deck> get freeDecks =>
      (super.noSuchMethod(
            Invocation.getter(#freeDecks),
            returnValue: <_i3.Deck>[],
          )
          as List<_i3.Deck>);

  @override
  List<_i3.Deck> get premiumDecks =>
      (super.noSuchMethod(
            Invocation.getter(#premiumDecks),
            returnValue: <_i3.Deck>[],
          )
          as List<_i3.Deck>);

  @override
  List<_i3.Deck> get unlockedDecks =>
      (super.noSuchMethod(
            Invocation.getter(#unlockedDecks),
            returnValue: <_i3.Deck>[],
          )
          as List<_i3.Deck>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<bool> createCustomDeck({
    required String? name,
    required String? description,
    required List<String>? cards,
    _i5.IconData? icon,
    _i6.Color? color,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createCustomDeck, [], {
              #name: name,
              #description: description,
              #cards: cards,
              #icon: icon,
              #color: color,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> updateCustomDeck({
    required String? deckId,
    String? name,
    String? description,
    List<String>? cards,
    _i5.IconData? icon,
    _i6.Color? color,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateCustomDeck, [], {
              #deckId: deckId,
              #name: name,
              #description: description,
              #cards: cards,
              #icon: icon,
              #color: color,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> deleteCustomDeck(String? deckId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCustomDeck, [deckId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> unlockPremiumDeck(String? deckId) =>
      (super.noSuchMethod(
            Invocation.method(#unlockPremiumDeck, [deckId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  bool isDeckUnlocked(String? deckId) =>
      (super.noSuchMethod(
            Invocation.method(#isDeckUnlocked, [deckId]),
            returnValue: false,
          )
          as bool);

  @override
  _i3.Deck? getDeckById(String? id) =>
      (super.noSuchMethod(Invocation.method(#getDeckById, [id])) as _i3.Deck?);

  @override
  List<_i3.Deck> searchDecks(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchDecks, [query]),
            returnValue: <_i3.Deck>[],
          )
          as List<_i3.Deck>);

  @override
  _i4.Future<List<String>> getRecentDeckIds() =>
      (super.noSuchMethod(
            Invocation.method(#getRecentDeckIds, []),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<void> addToRecentDecks(String? deckId) =>
      (super.noSuchMethod(
            Invocation.method(#addToRecentDecks, [deckId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i3.Deck>> getRecentDecks() =>
      (super.noSuchMethod(
            Invocation.method(#getRecentDecks, []),
            returnValue: _i4.Future<List<_i3.Deck>>.value(<_i3.Deck>[]),
          )
          as _i4.Future<List<_i3.Deck>>);

  @override
  _i4.Future<void> refreshData() =>
      (super.noSuchMethod(
            Invocation.method(#refreshData, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [GameProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameProvider extends _i1.Mock implements _i7.GameProvider {
  MockGameProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Duration get remainingTime =>
      (super.noSuchMethod(
            Invocation.getter(#remainingTime),
            returnValue: _FakeDuration_0(
              this,
              Invocation.getter(#remainingTime),
            ),
          )
          as Duration);

  @override
  bool get isGameActive =>
      (super.noSuchMethod(Invocation.getter(#isGameActive), returnValue: false)
          as bool);

  @override
  List<_i8.GameSession> get gameHistory =>
      (super.noSuchMethod(
            Invocation.getter(#gameHistory),
            returnValue: <_i8.GameSession>[],
          )
          as List<_i8.GameSession>);

  @override
  Map<String, dynamic> get statistics =>
      (super.noSuchMethod(
            Invocation.getter(#statistics),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  int get roundDuration =>
      (super.noSuchMethod(Invocation.getter(#roundDuration), returnValue: 0)
          as int);

  @override
  bool get soundEnabled =>
      (super.noSuchMethod(Invocation.getter(#soundEnabled), returnValue: false)
          as bool);

  @override
  bool get vibrationEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#vibrationEnabled),
            returnValue: false,
          )
          as bool);

  @override
  bool get kidFriendlyMode =>
      (super.noSuchMethod(
            Invocation.getter(#kidFriendlyMode),
            returnValue: false,
          )
          as bool);

  @override
  bool get showWordsAfterPass =>
      (super.noSuchMethod(
            Invocation.getter(#showWordsAfterPass),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void startGame({
    required _i3.Deck? deck,
    bool? isTeamMode = false,
    List<String>? teamNames,
    int? totalRounds = 1,
  }) => super.noSuchMethod(
    Invocation.method(#startGame, [], {
      #deck: deck,
      #isTeamMode: isTeamMode,
      #teamNames: teamNames,
      #totalRounds: totalRounds,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void markCorrect() => super.noSuchMethod(
    Invocation.method(#markCorrect, []),
    returnValueForMissingStub: null,
  );

  @override
  void markPass() => super.noSuchMethod(
    Invocation.method(#markPass, []),
    returnValueForMissingStub: null,
  );

  @override
  void togglePause() => super.noSuchMethod(
    Invocation.method(#togglePause, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> endGame() =>
      (super.noSuchMethod(
            Invocation.method(#endGame, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void nextTeam() => super.noSuchMethod(
    Invocation.method(#nextTeam, []),
    returnValueForMissingStub: null,
  );

  @override
  void playAgain() => super.noSuchMethod(
    Invocation.method(#playAgain, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> updateRoundDuration(int? seconds) =>
      (super.noSuchMethod(
            Invocation.method(#updateRoundDuration, [seconds]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> toggleSound() =>
      (super.noSuchMethod(
            Invocation.method(#toggleSound, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> toggleVibration() =>
      (super.noSuchMethod(
            Invocation.method(#toggleVibration, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> toggleKidFriendlyMode() =>
      (super.noSuchMethod(
            Invocation.method(#toggleKidFriendlyMode, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> toggleShowWordsAfterPass() =>
      (super.noSuchMethod(
            Invocation.method(#toggleShowWordsAfterPass, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getGlobalLeaderboard({
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getGlobalLeaderboard, [], {#limit: limit}),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getDeckLeaderboard(
    String? deckId, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDeckLeaderboard, [deckId], {#limit: limit}),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> refreshData() =>
      (super.noSuchMethod(
            Invocation.method(#refreshData, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  Map<String, dynamic> getStatistics() =>
      (super.noSuchMethod(
            Invocation.method(#getStatistics, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  Map<String, double> getAchievementProgress() =>
      (super.noSuchMethod(
            Invocation.method(#getAchievementProgress, []),
            returnValue: <String, double>{},
          )
          as Map<String, double>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
