import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';
import 'dart:io';
import '../models/video_recording_result.dart';
import '../services/game_replay_renderer.dart';
import 'video_overlay_frame_manager.dart';

class VideoWithOverlay extends StatefulWidget {
  final String videoPath;
  final VideoRecordingResult recordingResult;
  final Color deckColor;
  final VoidCallback? onTap;
  final bool autoPlay;
  final List<String>? preGeneratedFrames;

  const VideoWithOverlay({
    super.key,
    required this.videoPath,
    required this.recordingResult,
    required this.deckColor,
    this.onTap,
    this.autoPlay = false,
    this.preGeneratedFrames,
  });

  @override
  State<VideoWithOverlay> createState() => _VideoWithOverlayState();
}

class _VideoWithOverlayState extends State<VideoWithOverlay> {
  VideoPlayerController? _videoController;
  List<String> _gameFrames = [];
  int _currentFrameIndex = 0;
  bool _isGeneratingFrames = false;
  VideoOverlayFrameManager? _frameManager;

  @override
  void initState() {
    super.initState();
    _initializeVideo();
    _generateGameFrames();
  }

  Future<void> _initializeVideo() async {
    try {
      _videoController = VideoPlayerController.file(File(widget.videoPath));
      await _videoController!.initialize();

      // Update frame based on video position
      _videoController!.addListener(() {
        if (_videoController!.value.isPlaying && _gameFrames.isNotEmpty) {
          final position = _videoController!.value.position;
          // Calculate frame index for 30 FPS
          final frameIndex = (position.inMilliseconds * 30 / 1000).floor();

          if (frameIndex != _currentFrameIndex &&
              frameIndex >= 0 &&
              frameIndex < _gameFrames.length) {
            setState(() {
              _currentFrameIndex = frameIndex;
            });

            // Preload nearby frames
            _frameManager?.preloadFrames(frameIndex);
          }
        }
      });

      setState(() {});
    } catch (e) {
      debugPrint('Error initializing video: $e');
    }
  }

  Future<void> _generateGameFrames() async {
    // If frames are pre-generated, use them directly
    if (widget.preGeneratedFrames != null &&
        widget.preGeneratedFrames!.isNotEmpty) {
      setState(() {
        _gameFrames = widget.preGeneratedFrames!;
        _isGeneratingFrames = false;

        // Initialize frame manager
        _frameManager = VideoOverlayFrameManager(framePaths: _gameFrames);

        // Set context and preload after widget is built
        WidgetsBinding.instance.addPostFrameCallback((_) {
          if (mounted && _frameManager != null) {
            _frameManager!.setContext(context);
            _frameManager!.preloadFrames(0);
          }
        });
      });
      return;
    }

    // Otherwise generate frames
    setState(() {
      _isGeneratingFrames = true;
    });

    try {
      final frames = await GameReplayRenderer.generateGameReplayFrames(
        recordingResult: widget.recordingResult,
        deckColor: widget.deckColor,
        gameDuration: widget.recordingResult.duration,
      );

      if (mounted) {
        setState(() {
          _gameFrames = frames;
          _isGeneratingFrames = false;

          // Initialize frame manager
          _frameManager = VideoOverlayFrameManager(framePaths: frames);

          // Set context and preload after widget is built
          if (frames.isNotEmpty) {
            WidgetsBinding.instance.addPostFrameCallback((_) {
              if (mounted && _frameManager != null) {
                _frameManager!.setContext(context);
                _frameManager!.preloadFrames(0);
              }
            });
          }
        });
      }
    } catch (e) {
      debugPrint('Error generating game frames: $e');
      if (mounted) {
        setState(() {
          _isGeneratingFrames = false;
        });
      }
    }
  }

  @override
  void dispose() {
    _videoController?.dispose();
    _frameManager?.dispose();
    // Only clean up frame files if they were generated by this widget
    if (widget.preGeneratedFrames == null) {
      for (final frame in _gameFrames) {
        try {
          File(frame).deleteSync();
        } catch (e) {
          // Ignore errors
        }
      }
    }
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (_videoController == null || !_videoController!.value.isInitialized) {
      return Container(
        color: Colors.black,
        child: const Center(child: CircularProgressIndicator()),
      );
    }

    return GestureDetector(
      onTap: widget.onTap,
      child: Stack(
        fit: StackFit.expand,
        children: [
          // Main reaction video - mirrored to match natural front-camera perspective
          Container(
            color: Colors.black,
            child: Center(
              child: Transform(
                alignment: Alignment.center,
                transform: Matrix4.identity()..scale(-1.0, 1.0),
                child: AspectRatio(
                  aspectRatio: _videoController!.value.aspectRatio,
                  child: VideoPlayer(_videoController!),
                ),
              ),
            ),
          ),

          // Game overlay PiP - positioned bottom-left for consistency
          if (_gameFrames.isNotEmpty)
            Positioned(
              bottom: 20,
              left: 20,
              child: Container(
                width: 160,
                height: 120,
                decoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(12),
                  boxShadow: [
                    BoxShadow(
                      color: Colors.black.withOpacity(0.5),
                      blurRadius: 10,
                      offset: const Offset(0, 4),
                    ),
                  ],
                ),
                child: ClipRRect(
                  borderRadius: BorderRadius.circular(12),
                  child: AnimatedSwitcher(
                    duration: const Duration(milliseconds: 50),
                    child:
                        _currentFrameIndex < _gameFrames.length
                            ? _frameManager?.getFrame(_currentFrameIndex) ??
                                Image.file(
                                  File(_gameFrames[_currentFrameIndex]),
                                  key: ValueKey(_currentFrameIndex),
                                  fit: BoxFit.cover,
                                  errorBuilder: (context, error, stackTrace) {
                                    return Container(
                                      color: widget.deckColor.withOpacity(0.3),
                                      child: const Center(
                                        child: Icon(
                                          Icons.image_not_supported,
                                          color: Colors.white54,
                                        ),
                                      ),
                                    );
                                  },
                                )
                            : Container(
                              key: const ValueKey('empty'),
                              color: widget.deckColor.withOpacity(0.3),
                            ),
                  ),
                ),
              ),
            ),

          // Processing indicator
          if (_isGeneratingFrames)
            Positioned(
              bottom: 20,
              left: 20,
              child: Container(
                width: 160,
                height: 120,
                decoration: BoxDecoration(
                  color: Colors.black54,
                  borderRadius: BorderRadius.circular(12),
                ),
                child: const Center(
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      CircularProgressIndicator(
                        strokeWidth: 2,
                        valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
                      ),
                      SizedBox(height: 8),
                      Text(
                        'Generating overlay...',
                        style: TextStyle(color: Colors.white, fontSize: 11),
                      ),
                    ],
                  ),
                ),
              ),
            ),
        ],
      ),
    );
  }
}
