import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:video_player/video_player.dart';
import 'dart:io';
import '../constants/app_theme.dart';
import '../services/haptic_service.dart';
import '../models/video_recording_result.dart';
import '../services/game_replay_renderer.dart';
import '../widgets/video_overlay_frame_manager.dart';

class VideoPlayerWithOverlayScreen extends StatefulWidget {
  final String videoPath;
  final String title;
  final VideoRecordingResult recordingResult;
  final Color deckColor;
  final List<String>? preGeneratedFrames;

  const VideoPlayerWithOverlayScreen({
    super.key,
    required this.videoPath,
    required this.title,
    required this.recordingResult,
    required this.deckColor,
    this.preGeneratedFrames,
  });

  @override
  State<VideoPlayerWithOverlayScreen> createState() =>
      _VideoPlayerWithOverlayScreenState();
}

class _VideoPlayerWithOverlayScreenState
    extends State<VideoPlayerWithOverlayScreen> {
  final _hapticService = HapticService();
  VideoPlayerController? _controller;
  bool _isInitialized = false;
  bool _isPlaying = false;
  List<String> _gameFrames = [];
  int _currentFrameIndex = 0;
  bool _isGeneratingFrames = false;
  String? _generationError;
  VideoOverlayFrameManager? _frameManager;

  @override
  void initState() {
    super.initState();
    SystemChrome.setPreferredOrientations([
      DeviceOrientation.landscapeLeft,
      DeviceOrientation.landscapeRight,
    ]);
    _initializeVideo();
    _generateGameFrames();
  }

  Future<void> _initializeVideo() async {
    try {
      _controller = VideoPlayerController.file(File(widget.videoPath));
      await _controller!.initialize();

      // Update frame based on video position
      _controller!.addListener(() {
        if (_controller!.value.isPlaying && _gameFrames.isNotEmpty) {
          final position = _controller!.value.position;
          // Calculate frame index for 30 FPS
          final frameIndex = (position.inMilliseconds * 30 / 1000).floor();

          if (frameIndex != _currentFrameIndex &&
              frameIndex >= 0 &&
              frameIndex < _gameFrames.length) {
            setState(() {
              _currentFrameIndex = frameIndex;
            });

            // Preload nearby frames
            _frameManager?.preloadFrames(frameIndex);
          }
        }
      });

      setState(() {
        _isInitialized = true;
      });
    } catch (e) {
      debugPrint('Error initializing video: $e');
    }
  }

  Future<void> _generateGameFrames() async {
    // If frames are pre-generated, use them directly
    if (widget.preGeneratedFrames != null &&
        widget.preGeneratedFrames!.isNotEmpty) {
      debugPrint(
        'Using pre-generated frames: ${widget.preGeneratedFrames!.length} frames',
      );
      setState(() {
        _gameFrames = widget.preGeneratedFrames!;
        _isGeneratingFrames = false;

        // Initialize frame manager for smooth playback
        _frameManager = VideoOverlayFrameManager(
          framePaths: _gameFrames,
          context: context,
        );

        // Preload initial frames
        _frameManager!.preloadFrames(0);
      });
      return;
    }

    // Otherwise generate frames
    setState(() {
      _isGeneratingFrames = true;
      _generationError = null;
    });

    try {
      debugPrint('Starting frame generation for PiP overlay...');
      final frames = await GameReplayRenderer.generateGameReplayFrames(
        recordingResult: widget.recordingResult,
        deckColor: widget.deckColor,
        gameDuration: widget.recordingResult.duration,
      );

      debugPrint('Generated ${frames.length} frames for overlay');

      if (mounted) {
        setState(() {
          _gameFrames = frames;
          _isGeneratingFrames = false;

          // Initialize frame manager for smooth playback
          _frameManager = VideoOverlayFrameManager(
            framePaths: _gameFrames,
            context: context,
          );

          // Preload initial frames
          if (_gameFrames.isNotEmpty) {
            _frameManager!.preloadFrames(0);
          }
        });
      }
    } catch (e) {
      debugPrint('Error generating game frames: $e');
      if (mounted) {
        setState(() {
          _isGeneratingFrames = false;
          _generationError = e.toString();
        });
      }
    }
  }

  @override
  void dispose() {
    _controller?.dispose();
    _frameManager?.dispose();
    SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
      DeviceOrientation.portraitDown,
    ]);

    // Only clean up frame files if they were generated by this screen
    if (widget.preGeneratedFrames == null) {
      for (final frame in _gameFrames) {
        try {
          File(frame).deleteSync();
        } catch (e) {
          // Ignore errors
        }
      }
    }
    super.dispose();
  }

  void _togglePlayPause() {
    if (_controller == null) return;

    setState(() {
      if (_controller!.value.isPlaying) {
        _controller!.pause();
        _isPlaying = false;
      } else {
        _controller!.play();
        _isPlaying = true;
      }
    });
    _hapticService.lightImpact();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      body: Stack(
        children: [
          // Video player
          if (_isInitialized && _controller != null)
            Center(
              child: AspectRatio(
                aspectRatio: _controller!.value.aspectRatio,
                child: VideoPlayer(_controller!),
              ),
            )
          else
            const Center(
              child: CircularProgressIndicator(
                valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
              ),
            ),

          // PiP overlay
          if (_gameFrames.isNotEmpty && _isInitialized)
            Positioned(
              bottom: 100,
              right: 20,
              child: Container(
                width: 200,
                height: 150,
                decoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(12),
                  boxShadow: [
                    BoxShadow(
                      color: Colors.black.withOpacity(0.5),
                      blurRadius: 10,
                      offset: const Offset(0, 4),
                    ),
                  ],
                ),
                child: ClipRRect(
                  borderRadius: BorderRadius.circular(12),
                  child: Stack(
                    children: [
                      AnimatedSwitcher(
                        duration: const Duration(milliseconds: 50),
                        child:
                            _currentFrameIndex < _gameFrames.length
                                ? _frameManager?.getFrame(_currentFrameIndex) ??
                                    Image.file(
                                      File(_gameFrames[_currentFrameIndex]),
                                      key: ValueKey(_currentFrameIndex),
                                      fit: BoxFit.cover,
                                      errorBuilder: (
                                        context,
                                        error,
                                        stackTrace,
                                      ) {
                                        return Container(
                                          color: widget.deckColor.withOpacity(
                                            0.3,
                                          ),
                                          child: const Center(
                                            child: Icon(
                                              Icons.image_not_supported,
                                              color: Colors.white54,
                                            ),
                                          ),
                                        );
                                      },
                                    )
                                : Container(
                                  key: const ValueKey('empty'),
                                  color: widget.deckColor.withOpacity(0.3),
                                  child: const Center(
                                    child: Text(
                                      'Game Replay',
                                      style: TextStyle(
                                        color: Colors.white,
                                        fontSize: 12,
                                      ),
                                    ),
                                  ),
                                ),
                      ),

                      // Frame number debug (optional - remove in production)
                      if (false) // Set to true for debugging
                        Positioned(
                          top: 4,
                          left: 4,
                          child: Container(
                            padding: const EdgeInsets.symmetric(
                              horizontal: 6,
                              vertical: 2,
                            ),
                            decoration: BoxDecoration(
                              color: Colors.black54,
                              borderRadius: BorderRadius.circular(4),
                            ),
                            child: Text(
                              'Frame ${_currentFrameIndex + 1}/${_gameFrames.length}',
                              style: const TextStyle(
                                color: Colors.white,
                                fontSize: 10,
                              ),
                            ),
                          ),
                        ),
                    ],
                  ),
                ),
              ),
            ),

          // Processing indicator for overlay
          if (_isGeneratingFrames)
            Positioned(
              bottom: 100,
              right: 20,
              child: Container(
                width: 200,
                height: 150,
                decoration: BoxDecoration(
                  color: Colors.black54,
                  borderRadius: BorderRadius.circular(12),
                ),
                child: Center(
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      const CircularProgressIndicator(
                        strokeWidth: 2,
                        valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
                      ),
                      const SizedBox(height: 8),
                      Text(
                        'Generating overlay...',
                        style: const TextStyle(
                          color: Colors.white,
                          fontSize: 11,
                        ),
                      ),
                      if (_generationError != null)
                        Padding(
                          padding: const EdgeInsets.only(top: 8),
                          child: Text(
                            'Error: $_generationError',
                            style: const TextStyle(
                              color: Colors.red,
                              fontSize: 10,
                            ),
                            textAlign: TextAlign.center,
                          ),
                        ),
                    ],
                  ),
                ),
              ),
            ),

          // Controls overlay
          if (_isInitialized)
            GestureDetector(
              onTap: _togglePlayPause,
              child: Container(
                color: Colors.transparent,
                child: Center(
                  child: AnimatedOpacity(
                    opacity: _isPlaying ? 0.0 : 1.0,
                    duration: const Duration(milliseconds: 300),
                    child: Container(
                      width: 80,
                      height: 80,
                      decoration: BoxDecoration(
                        color: Colors.black54,
                        shape: BoxShape.circle,
                      ),
                      child: Icon(
                        _isPlaying ? Icons.pause : Icons.play_arrow,
                        color: Colors.white,
                        size: 50,
                      ),
                    ),
                  ),
                ),
              ),
            ),

          // Header with back button
          SafeArea(
            child: Container(
              padding: const EdgeInsets.all(16),
              child: Row(
                children: [
                  IconButton(
                    icon: const Icon(Icons.arrow_back, color: Colors.white),
                    onPressed: () => Navigator.pop(context),
                  ),
                  const SizedBox(width: 8),
                  Expanded(
                    child: Text(
                      widget.title,
                      style: const TextStyle(
                        color: Colors.white,
                        fontSize: 18,
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ),

          // Video controls
          if (_isInitialized && _controller != null)
            Positioned(
              left: 0,
              right: 0,
              bottom: 0,
              child: Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  gradient: LinearGradient(
                    begin: Alignment.bottomCenter,
                    end: Alignment.topCenter,
                    colors: [Colors.black87, Colors.transparent],
                  ),
                ),
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    // Progress bar
                    VideoProgressIndicator(
                      _controller!,
                      allowScrubbing: true,
                      colors: VideoProgressColors(
                        playedColor: AppTheme.primaryColor,
                        bufferedColor: Colors.white24,
                        backgroundColor: Colors.white12,
                      ),
                    ),
                    const SizedBox(height: 8),
                    // Time display
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Text(
                          _formatDuration(_controller!.value.position),
                          style: const TextStyle(
                            color: Colors.white,
                            fontSize: 12,
                          ),
                        ),
                        Text(
                          _formatDuration(_controller!.value.duration),
                          style: const TextStyle(
                            color: Colors.white,
                            fontSize: 12,
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ),
        ],
      ),
    );
  }

  String _formatDuration(Duration duration) {
    final minutes = duration.inMinutes.remainder(60).toString().padLeft(2, '0');
    final seconds = duration.inSeconds.remainder(60).toString().padLeft(2, '0');
    return '$minutes:$seconds';
  }
}
