import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

// Run this script to populate Firebase with sample decks
// flutter run lib/scripts/populate_firebase_decks.dart

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  
  print('🚀 Starting deck population...');
  
  final firestore = FirebaseFirestore.instance;
  final batch = firestore.batch();
  
  final sampleDecks = [
    // UNIVERSAL DECKS
    {
      'name': 'Viral TikTok Trends',
      'description': 'Guess the latest TikTok trends and challenges',
      'country': 'UNIVERSAL',
      'iconCodePoint': FontAwesomeIcons.tiktok.codePoint,
      'iconFontFamily': 'FontAwesomeBrands',
      'colorValue': const Color(0xFF000000).value,
      'isPremium': false,
      'priority': 1,
      'isActive': true,
      'tags': ['social', 'trending', 'viral', 'dance'],
      'cards': [
        'Renegade Dance',
        'Savage Love',
        'WAP Dance',
        'Silhouette Challenge',
        'Buss It Challenge',
        'Tell Me Without Telling Me',
        'Corn Kid',
        'Wednesday Dance',
        "It's Corn!",
        'Ohio Memes',
        'Girl Dinner',
        'Roman Empire Trend',
        'NPC Streaming',
        'Grimace Shake',
        'Delulu',
      ],
    },
    {
      'name': 'Netflix Originals',
      'description': 'Popular Netflix shows and movies',
      'country': 'UNIVERSAL',
      'iconCodePoint': FontAwesomeIcons.film.codePoint,
      'iconFontFamily': 'FontAwesomeSolid',
      'colorValue': const Color(0xFFE50914).value,
      'isPremium': false,
      'priority': 2,
      'isActive': true,
      'tags': ['movies', 'streaming', 'entertainment'],
      'cards': [
        'Stranger Things',
        'Wednesday',
        'Squid Game',
        'Money Heist',
        'The Crown',
        'Bridgerton',
        'The Witcher',
        'Ozark',
        'Black Mirror',
        'Orange Is the New Black',
        "The Queen's Gambit",
        'Tiger King',
        'Love Is Blind',
        'The Umbrella Academy',
        'Lucifer',
      ],
    },
    {
      'name': 'Gaming Icons',
      'description': 'Popular video game characters and titles',
      'country': 'UNIVERSAL',
      'iconCodePoint': FontAwesomeIcons.gamepad.codePoint,
      'iconFontFamily': 'FontAwesomeSolid',
      'colorValue': const Color(0xFF9146FF).value,
      'isPremium': false,
      'priority': 3,
      'isActive': true,
      'tags': ['gaming', 'esports', 'entertainment'],
      'cards': [
        'Fortnite',
        'Minecraft',
        'Roblox',
        'Among Us',
        'Call of Duty',
        'Grand Theft Auto',
        'Pokemon',
        'Super Mario',
        'Zelda',
        'FIFA',
        'Apex Legends',
        'Valorant',
        'League of Legends',
        'Overwatch',
        'Fall Guys',
      ],
    },

    // INDIA DECKS
    {
      'name': 'Bollywood Superstars',
      'description': 'Iconic Bollywood actors and actresses',
      'country': 'IN',
      'iconCodePoint': FontAwesomeIcons.film.codePoint,
      'iconFontFamily': 'FontAwesomeSolid',
      'colorValue': const Color(0xFFFF9933).value,
      'isPremium': false,
      'priority': 1,
      'isActive': true,
      'tags': ['bollywood', 'movies', 'india', 'entertainment'],
      'cards': [
        'Shah Rukh Khan',
        'Salman Khan',
        'Aamir Khan',
        'Amitabh Bachchan',
        'Deepika Padukone',
        'Priyanka Chopra',
        'Alia Bhatt',
        'Ranveer Singh',
        'Ranbir Kapoor',
        'Kareena Kapoor',
        'Katrina Kaif',
        'Akshay Kumar',
        'Hrithik Roshan',
        'Varun Dhawan',
        'Anushka Sharma',
      ],
    },
    {
      'name': 'Cricket Legends',
      'description': 'Famous Indian cricket players',
      'country': 'IN',
      'iconCodePoint': FontAwesomeIcons.baseball.codePoint,
      'iconFontFamily': 'FontAwesomeSolid',
      'colorValue': const Color(0xFF138808).value,
      'isPremium': false,
      'priority': 2,
      'isActive': true,
      'tags': ['cricket', 'sports', 'india'],
      'cards': [
        'Virat Kohli',
        'MS Dhoni',
        'Sachin Tendulkar',
        'Rohit Sharma',
        'Kapil Dev',
        'Sunil Gavaskar',
        'Rahul Dravid',
        'Sourav Ganguly',
        'Yuvraj Singh',
        'Hardik Pandya',
        'Jasprit Bumrah',
        'Ravindra Jadeja',
        'KL Rahul',
        'Shikhar Dhawan',
        'Rishabh Pant',
      ],
    },
    {
      'name': 'Indian Street Food',
      'description': 'Delicious street food from across India',
      'country': 'IN',
      'iconCodePoint': FontAwesomeIcons.utensils.codePoint,
      'iconFontFamily': 'FontAwesomeSolid',
      'colorValue': const Color(0xFFFF6347).value,
      'isPremium': false,
      'priority': 3,
      'isActive': true,
      'tags': ['food', 'cuisine', 'india', 'street food'],
      'cards': [
        'Pani Puri',
        'Vada Pav',
        'Dosa',
        'Samosa',
        'Chole Bhature',
        'Pav Bhaji',
        'Biryani',
        'Momos',
        'Jalebi',
        'Chaat',
        'Kachori',
        'Aloo Tikki',
        'Bhel Puri',
        'Kulfi',
        'Lassi',
      ],
    },
    {
      'name': 'Indian Web Series',
      'description': 'Popular Indian streaming shows',
      'country': 'IN',
      'iconCodePoint': FontAwesomeIcons.tv.codePoint,
      'iconFontFamily': 'FontAwesomeSolid',
      'colorValue': const Color(0xFF673AB7).value,
      'isPremium': true,
      'priority': 4,
      'isActive': true,
      'tags': ['web series', 'streaming', 'india', 'entertainment'],
      'cards': [
        'Mirzapur',
        'Sacred Games',
        'The Family Man',
        'Scam 1992',
        'Panchayat',
        'Kota Factory',
        'Aspirants',
        'Criminal Justice',
        'Made in Heaven',
        'Four More Shots Please',
        'Bandish Bandits',
        'Aarya',
        'Mumbai Diaries',
        'Rocket Boys',
        'The Fame Game',
      ],
    },

    // USA DECKS
    {
      'name': 'NFL Stars',
      'description': 'Famous NFL players',
      'country': 'US',
      'iconCodePoint': FontAwesomeIcons.footballBall.codePoint,
      'iconFontFamily': 'FontAwesomeSolid',
      'colorValue': const Color(0xFF013369).value,
      'isPremium': false,
      'priority': 1,
      'isActive': true,
      'tags': ['sports', 'nfl', 'football', 'usa'],
      'cards': [
        'Tom Brady',
        'Patrick Mahomes',
        'Aaron Rodgers',
        'Lamar Jackson',
        'Travis Kelce',
        'Justin Jefferson',
        'Josh Allen',
        'Dak Prescott',
        'Joe Burrow',
        'Russell Wilson',
        'Jalen Hurts',
        'Nick Bosa',
        'TJ Watt',
        'Micah Parsons',
        'Tyreek Hill',
      ],
    },
    {
      'name': 'American Fast Food',
      'description': 'Popular fast food chains in America',
      'country': 'US',
      'iconCodePoint': FontAwesomeIcons.hamburger.codePoint,
      'iconFontFamily': 'FontAwesomeSolid',
      'colorValue': const Color(0xFFFF0000).value,
      'isPremium': false,
      'priority': 2,
      'isActive': true,
      'tags': ['food', 'fast food', 'usa', 'restaurants'],
      'cards': [
        "McDonald's",
        'Burger King',
        "Wendy's",
        'Taco Bell',
        'KFC',
        'Subway',
        'Chick-fil-A',
        'Pizza Hut',
        "Domino's",
        'Chipotle',
        'Five Guys',
        'In-N-Out',
        'Popeyes',
        "Arby's",
        'Sonic',
      ],
    },

    // JAPAN DECKS
    {
      'name': 'Anime Characters',
      'description': 'Famous anime characters',
      'country': 'JP',
      'iconCodePoint': FontAwesomeIcons.dragon.codePoint,
      'iconFontFamily': 'FontAwesomeSolid',
      'colorValue': const Color(0xFFBC002D).value,
      'isPremium': true,
      'priority': 1,
      'isActive': true,
      'tags': ['anime', 'manga', 'japan', 'entertainment'],
      'cards': [
        'Naruto',
        'Goku',
        'Luffy',
        'Light Yagami',
        'Eren Yeager',
        'Sailor Moon',
        'Pikachu',
        'Ichigo',
        'Levi Ackerman',
        'All Might',
        'Saitama',
        'Vegeta',
        'Todoroki',
        'Nezuko',
        'Edward Elric',
      ],
    },
    {
      'name': 'Japanese Food',
      'description': 'Traditional Japanese cuisine',
      'country': 'JP',
      'iconCodePoint': FontAwesomeIcons.utensils.codePoint,
      'iconFontFamily': 'FontAwesomeSolid',
      'colorValue': const Color(0xFFE60012).value,
      'isPremium': false,
      'priority': 2,
      'isActive': true,
      'tags': ['food', 'cuisine', 'japan', 'sushi'],
      'cards': [
        'Sushi',
        'Ramen',
        'Tempura',
        'Sashimi',
        'Udon',
        'Miso Soup',
        'Tonkatsu',
        'Yakitori',
        'Onigiri',
        'Takoyaki',
        'Okonomiyaki',
        'Matcha',
        'Mochi',
        'Bento',
        'Teriyaki',
      ],
    },

    // K-POP DECK (Korea)
    {
      'name': 'K-Pop Groups',
      'description': 'Popular Korean pop groups',
      'country': 'KR',
      'iconCodePoint': FontAwesomeIcons.music.codePoint,
      'iconFontFamily': 'FontAwesomeSolid',
      'colorValue': const Color(0xFFFF0099).value,
      'isPremium': true,
      'priority': 1,
      'isActive': true,
      'tags': ['kpop', 'music', 'korea', 'entertainment'],
      'cards': [
        'BTS',
        'BLACKPINK',
        'Stray Kids',
        'SEVENTEEN',
        'TWICE',
        'NCT',
        'ENHYPEN',
        'ATEEZ',
        'TXT',
        'ITZY',
        'aespa',
        'NewJeans',
        'LE SSERAFIM',
        'IVE',
        'TREASURE',
      ],
    },

    // TRENDING 2025
    {
      'name': 'Trending 2025',
      'description': "What's hot in 2025",
      'country': 'TRENDING',
      'iconCodePoint': FontAwesomeIcons.fire.codePoint,
      'iconFontFamily': 'FontAwesomeSolid',
      'colorValue': const Color(0xFFFF6B6B).value,
      'isPremium': false,
      'priority': 0, // Highest priority
      'isActive': true,
      'tags': ['trending', 'viral', '2025', 'hot'],
      'cards': [
        'AI Assistants',
        'Vision Pro',
        'Threads App',
        'ChatGPT',
        'BeReal',
        'Quiet Luxury',
        'Girl Math',
        'Deinfluencing',
        'Digital Detox',
        'Eco Anxiety',
        'Rizz',
        'No Cap',
        'Slay',
        'Bet',
        'Bussin',
      ],
    },
  ];

  // Add each deck to the batch
  for (final deck in sampleDecks) {
    final docRef = firestore.collection('decks').doc();
    batch.set(docRef, {
      ...deck,
      'createdAt': FieldValue.serverTimestamp(),
      'updatedAt': FieldValue.serverTimestamp(),
    });
  }

  try {
    await batch.commit();
    print('✅ Successfully added ${sampleDecks.length} decks to Firebase!');
    
    // Show summary
    print('\n📊 Summary:');
    print('- Universal decks: ${sampleDecks.where((d) => d['country'] == 'UNIVERSAL').length}');
    print('- India decks: ${sampleDecks.where((d) => d['country'] == 'IN').length}');
    print('- USA decks: ${sampleDecks.where((d) => d['country'] == 'US').length}');
    print('- Japan decks: ${sampleDecks.where((d) => d['country'] == 'JP').length}');
    print('- Korea decks: ${sampleDecks.where((d) => d['country'] == 'KR').length}');
    print('- Trending decks: ${sampleDecks.where((d) => d['country'] == 'TRENDING').length}');
    
  } catch (e) {
    print('❌ Error populating decks: $e');
  }
}
