import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  final firestore = FirebaseFirestore.instance;

  print('Starting to populate Firebase with sample data...');

  // Sample decks data
  final List<Map<String, dynamic>> sampleDecks = [
    {
      'id': 'celebrities',
      'name': 'Celebrities',
      'description': 'Famous actors, musicians, and public figures',
      'category': 'Entertainment',
      'difficulty': 'Easy',
      'iconName': 'star',
      'isPremium': false,
      'cards': [
        'Brad Pitt',
        'Angelina Jolie',
        'Tom Cruise',
        'Jennifer Lawrence',
        'Leonardo DiCaprio',
        'Scarlett Johansson',
        'Robert Downey Jr.',
        'Chris Hemsworth',
        'Emma Watson',
        'Ryan Reynolds',
        'Will Smith',
        'Johnny Depp',
        'Meryl Streep',
        'Tom Hanks',
        'Julia Roberts',
        'George Clooney',
        'Matt Damon',
        'Benedict Cumberbatch',
        'Morgan Freeman',
        'Samuel L. Jackson',
        'Denzel Washington',
        'Nicole Kidman',
        'Charlize Theron',
        'Anne Hathaway',
        'Emma Stone',
      ],
      'createdAt': FieldValue.serverTimestamp(),
      'updatedAt': FieldValue.serverTimestamp(),
      'playCount': 150,
      'rating': 4.5,
    },
    {
      'id': 'animals',
      'name': 'Animals',
      'description': 'Creatures from around the world',
      'category': 'Nature',
      'difficulty': 'Easy',
      'iconName': 'pets',
      'isPremium': false,
      'cards': [
        'Lion',
        'Tiger',
        'Elephant',
        'Giraffe',
        'Zebra',
        'Monkey',
        'Kangaroo',
        'Penguin',
        'Dolphin',
        'Whale',
        'Shark',
        'Octopus',
        'Eagle',
        'Owl',
        'Parrot',
        'Flamingo',
        'Peacock',
        'Butterfly',
        'Bee',
        'Ant',
        'Spider',
        'Snake',
        'Crocodile',
        'Turtle',
        'Frog',
        'Bear',
        'Wolf',
        'Fox',
        'Rabbit',
        'Squirrel',
      ],
      'createdAt': FieldValue.serverTimestamp(),
      'updatedAt': FieldValue.serverTimestamp(),
      'playCount': 200,
      'rating': 4.7,
    },
    {
      'id': 'movies',
      'name': 'Movies',
      'description': 'Popular films and blockbusters',
      'category': 'Entertainment',
      'difficulty': 'Medium',
      'iconName': 'movie',
      'isPremium': false,
      'cards': [
        'The Godfather',
        'Star Wars',
        'The Dark Knight',
        'Pulp Fiction',
        'Forrest Gump',
        'Inception',
        'The Matrix',
        'Goodfellas',
        'The Shawshank Redemption',
        'Fight Club',
        'The Lord of the Rings',
        'Harry Potter',
        'The Avengers',
        'Titanic',
        'Jurassic Park',
        'E.T.',
        'Back to the Future',
        'Jaws',
        'Indiana Jones',
        'Terminator',
        'Die Hard',
        'Alien',
        'The Silence of the Lambs',
        'Gladiator',
        'Braveheart',
        'The Lion King',
        'Toy Story',
        'Finding Nemo',
        'Shrek',
        'Frozen',
      ],
      'createdAt': FieldValue.serverTimestamp(),
      'updatedAt': FieldValue.serverTimestamp(),
      'playCount': 175,
      'rating': 4.6,
    },
    {
      'id': 'sports',
      'name': 'Sports & Athletes',
      'description': 'Sports, teams, and famous athletes',
      'category': 'Sports',
      'difficulty': 'Medium',
      'iconName': 'sports_soccer',
      'isPremium': false,
      'cards': [
        'Football',
        'Basketball',
        'Baseball',
        'Soccer',
        'Tennis',
        'Golf',
        'Boxing',
        'Swimming',
        'Running',
        'Cycling',
        'Michael Jordan',
        'LeBron James',
        'Tom Brady',
        'Cristiano Ronaldo',
        'Lionel Messi',
        'Serena Williams',
        'Tiger Woods',
        'Muhammad Ali',
        'Mike Tyson',
        'Usain Bolt',
        'Michael Phelps',
        'Roger Federer',
        'Rafael Nadal',
        'Kobe Bryant',
        'Shaquille O\'Neal',
        'Wayne Gretzky',
        'Olympics',
        'World Cup',
        'Super Bowl',
        'NBA Finals',
      ],
      'createdAt': FieldValue.serverTimestamp(),
      'updatedAt': FieldValue.serverTimestamp(),
      'playCount': 120,
      'rating': 4.4,
    },
    {
      'id': 'food',
      'name': 'Food & Drinks',
      'description': 'Delicious dishes and beverages',
      'category': 'Lifestyle',
      'difficulty': 'Easy',
      'iconName': 'restaurant',
      'isPremium': false,
      'cards': [
        'Pizza',
        'Burger',
        'Pasta',
        'Sushi',
        'Tacos',
        'Sandwich',
        'Salad',
        'Soup',
        'Steak',
        'Chicken',
        'Fish',
        'Rice',
        'Bread',
        'Cheese',
        'Ice Cream',
        'Cake',
        'Chocolate',
        'Cookies',
        'Coffee',
        'Tea',
        'Juice',
        'Soda',
        'Water',
        'Milk',
        'Wine',
        'Beer',
        'Cocktail',
        'Smoothie',
        'French Fries',
        'Popcorn',
        'Chips',
        'Candy',
        'Fruit',
        'Vegetables',
      ],
      'createdAt': FieldValue.serverTimestamp(),
      'updatedAt': FieldValue.serverTimestamp(),
      'playCount': 95,
      'rating': 4.3,
    },
    {
      'id': 'music',
      'name': 'Music & Bands',
      'description': 'Songs, artists, and musical instruments',
      'category': 'Entertainment',
      'difficulty': 'Medium',
      'iconName': 'music_note',
      'isPremium': true,
      'cards': [
        'The Beatles',
        'Elvis Presley',
        'Michael Jackson',
        'Madonna',
        'Queen',
        'David Bowie',
        'Prince',
        'Bob Dylan',
        'The Rolling Stones',
        'Led Zeppelin',
        'Pink Floyd',
        'AC/DC',
        'Metallica',
        'Nirvana',
        'Beyoncé',
        'Taylor Swift',
        'Adele',
        'Ed Sheeran',
        'Drake',
        'Eminem',
        'Jay-Z',
        'Kanye West',
        'Rihanna',
        'Lady Gaga',
        'Bruno Mars',
        'Justin Bieber',
        'Ariana Grande',
        'Billie Eilish',
        'Guitar',
        'Piano',
        'Drums',
        'Violin',
        'Saxophone',
      ],
      'createdAt': FieldValue.serverTimestamp(),
      'updatedAt': FieldValue.serverTimestamp(),
      'playCount': 160,
      'rating': 4.8,
    },
    {
      'id': 'technology',
      'name': 'Technology',
      'description': 'Gadgets, apps, and tech companies',
      'category': 'Science',
      'difficulty': 'Hard',
      'iconName': 'computer',
      'isPremium': true,
      'cards': [
        'iPhone',
        'Android',
        'Computer',
        'Laptop',
        'Tablet',
        'Smartphone',
        'Internet',
        'WiFi',
        'Bluetooth',
        'GPS',
        'Apple',
        'Google',
        'Microsoft',
        'Amazon',
        'Facebook',
        'Instagram',
        'Twitter',
        'TikTok',
        'YouTube',
        'Netflix',
        'Spotify',
        'Uber',
        'Airbnb',
        'Tesla',
        'SpaceX',
        'Artificial Intelligence',
        'Virtual Reality',
        'Blockchain',
        'Cryptocurrency',
        'Bitcoin',
        'Programming',
        'Coding',
        'Robot',
        'Drone',
        '3D Printing',
      ],
      'createdAt': FieldValue.serverTimestamp(),
      'updatedAt': FieldValue.serverTimestamp(),
      'playCount': 85,
      'rating': 4.2,
    },
    {
      'id': 'countries',
      'name': 'Countries & Cities',
      'description': 'Places around the world',
      'category': 'Geography',
      'difficulty': 'Medium',
      'iconName': 'public',
      'isPremium': false,
      'cards': [
        'United States',
        'Canada',
        'Mexico',
        'Brazil',
        'Argentina',
        'United Kingdom',
        'France',
        'Germany',
        'Italy',
        'Spain',
        'Russia',
        'China',
        'Japan',
        'India',
        'Australia',
        'Egypt',
        'South Africa',
        'New York',
        'Los Angeles',
        'London',
        'Paris',
        'Tokyo',
        'Sydney',
        'Dubai',
        'Singapore',
        'Rome',
        'Berlin',
        'Madrid',
        'Amsterdam',
        'Bangkok',
      ],
      'createdAt': FieldValue.serverTimestamp(),
      'updatedAt': FieldValue.serverTimestamp(),
      'playCount': 110,
      'rating': 4.5,
    },
    {
      'id': 'actions',
      'name': 'Actions',
      'description': 'Act out these verbs and activities',
      'category': 'Classic',
      'difficulty': 'Easy',
      'iconName': 'directions_run',
      'isPremium': false,
      'cards': [
        'Running',
        'Jumping',
        'Dancing',
        'Singing',
        'Sleeping',
        'Eating',
        'Drinking',
        'Cooking',
        'Driving',
        'Flying',
        'Swimming',
        'Climbing',
        'Crawling',
        'Walking',
        'Sitting',
        'Standing',
        'Laughing',
        'Crying',
        'Smiling',
        'Winking',
        'Waving',
        'Clapping',
        'Pointing',
        'Pushing',
        'Pulling',
        'Throwing',
        'Catching',
        'Kicking',
        'Punching',
        'Hugging',
      ],
      'createdAt': FieldValue.serverTimestamp(),
      'updatedAt': FieldValue.serverTimestamp(),
      'playCount': 140,
      'rating': 4.6,
    },
    {
      'id': 'superheroes',
      'name': 'Superheroes',
      'description': 'Comic book heroes and villains',
      'category': 'Entertainment',
      'difficulty': 'Easy',
      'iconName': 'flash_on',
      'isPremium': true,
      'cards': [
        'Superman',
        'Batman',
        'Spider-Man',
        'Iron Man',
        'Captain America',
        'Thor',
        'Hulk',
        'Black Widow',
        'Wonder Woman',
        'Aquaman',
        'The Flash',
        'Green Lantern',
        'Wolverine',
        'Deadpool',
        'Black Panther',
        'Doctor Strange',
        'Ant-Man',
        'Captain Marvel',
        'Scarlet Witch',
        'Vision',
        'Thanos',
        'Joker',
        'Lex Luthor',
        'Green Goblin',
        'Magneto',
        'Loki',
        'Venom',
        'Harley Quinn',
        'Catwoman',
        'Robin',
      ],
      'createdAt': FieldValue.serverTimestamp(),
      'updatedAt': FieldValue.serverTimestamp(),
      'playCount': 125,
      'rating': 4.7,
    },
  ];

  // Populate decks
  print('Populating decks...');
  WriteBatch batch = firestore.batch();

  for (var deckData in sampleDecks) {
    final deckRef = firestore.collection('decks').doc(deckData['id']);
    batch.set(deckRef, deckData);
    print('Added deck: ${deckData['name']}');
  }

  // Commit the batch
  await batch.commit();
  print('Successfully populated ${sampleDecks.length} decks!');

  // Add some sample user statistics (optional)
  print('\nAdding sample statistics...');
  final statsRef = firestore.collection('statistics').doc('global');
  await statsRef.set({
    'totalGamesPlayed': 1250,
    'totalUsers': 342,
    'mostPlayedDeck': 'animals',
    'averageGameDuration': 180, // seconds
    'lastUpdated': FieldValue.serverTimestamp(),
  });

  print('Sample statistics added!');
  print('\n✅ Firebase population complete!');
  print('You can now run the app and see the populated data.');
}
